global:
  scrape_interval: 5s

scrape_configs:
  - job_name: api-gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["api-gateway:8080"]

  - job_name: fraud-engine-service
    metrics_path: /fraud-service/actuator/prometheus
    static_configs:
      - targets: ["fraud-engine-service:8081"]
